device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.SI_SNRi
    device: ${metrics.device}
    name: "SI-SNRi"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SI_SNRi
    device: ${metrics.device}
    name: "SI-SNRi"
  # - _target_: src.metrics.STOI # supports only cpu (t.w. only inference)
  #   device: ${metrics.device}
  #   name: "VAL_STOI"
  # - _target_: src.metrics.PESQ
  #   device: ${metrics.device}
  #   name: "VAL_PESQ"
  - _target_: src.metrics.SDRi
    device: ${metrics.device}
    name: "SDRi"
