_target_: src.model.ConvTasNet

encoder_params:
  input_channels: 1
  output_channels: 512
  kernel_size: 64
  stride: 32

separator_params:
    input_channels: 512
    bottleneck_channels: 128
    n_blocks: 8
    kernel_size: 3
    n_sources: 2

decoder_params:
    input_channels: 512
    kernel_size: 64
    stride: 32