_target_: src.model.ConvTasNet

encoder_params:
  input_channels: 1
  kernel_size: 32
  output_channels: 512
  stride: 16

separator_params:
  bottleneck_channels: 128
  input_channels: 512
  kernel_size: 3
  n_blocks: 12
  n_sources: 2
  n_repeats: 3

decoder_params:
  input_channels: 512
  kernel_size: 32
  stride: 16
