_target_: src.model.ConvTasNet

encoder_params:
  input_channels: 1
  output_channels: 512
  kernel_size: 20
  stride: 10

separator_params:
  bottleneck_channels: 128
  input_channels: 512
  kernel_size: 3
  n_blocks: 11
  n_sources: 2
  n_repeats: 3

decoder_params:
  input_channels: 512
  kernel_size: 20
  stride: 10
