defaults:
  - model: convtasnet
  - writer: wandb
  - metrics: audio_metrics
  - datasets: av
  - dataloader: convtasnet
  - transforms: example_only_batch
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.9995
loss_function:
  _target_: src.loss.SiSNR_PIT
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: null
  device_tensors: ["audio_mix", "audio_s1", "audio_s2"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max val_VAL_SI-SNRi" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 7
  max_grad_norm: 500.0
