defaults:
  - model: convtasnet
  - metrics: audio_metrics
  - datasets: av_test
  - dataloader: example
  - transforms: example_only_batch
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "/Users/georgijfatahov/Downloads/best/saved/baseline_v2_bigger/model_best.pth" # path to the pretrained model
