defaults:
  - model: convtasnet
  - metrics: test
  - datasets: av_test
  - dataloader: example
  - transforms: example_only_batch
  - _self_
inferencer:
  device_tensors: [ "audio_mix" ]
  device: auto # device name or "auto"
  save_path: "" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "" # path to the pretrained model
