train:
  audio_mix: # name of the tensor on which we apply transform
    _target_: src.transforms.AddRir
    apply_prob: 0.7
    pointsource_noises: True
    real_rirs_isotropic_noises: True
    simulated_rirs: False
inference: null
